name: Run tests and lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # VITEST JOB
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn ci
      - name: Run Vitest
        run: yarn test
  # ESLINT JOB
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn ci
      - name: Run lint
        run: yarn lint
